spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dqd
    username: root
    password: 123456pkh
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: com.software.engine.entity